name: update-inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 6'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install nix
      uses: DeterminateSystems/nix-installer-action@v2
    - name: set up nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: update inputs
      uses: DeterminateSystems/update-flake-lock@v19
      with:
        inputs: nixpkgs crane fenix
        pr-title: "Update flake inputs"
        git-author-name: 'Mark Pashmfouroush'
        git-author-email: 'mark@markpash.me'
        git-committer-name: 'Mark Pashmfouroush'
        git-committer-email: 'mark@markpash.me'
