name: update-packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "master"

jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        package:
          - "age"
          - "bepass-relay"
          - "bepass"
          - "brook"
          - "chisel"
          - "clash-meta"
          - "clash"
          - "cloak"
          - "daze"
          - "dive"
          - "dnscrypt-proxy2"
          - "dtlspipe"
          - "gg"
          - "glider"
          - "go-shadowsocks2"
          - "gost"
          - "headscale"
          - "hysteria"
          - "juicity"
          - "lyrebird"
          - "mieru"
          - "mtg"
          - "mwgp"
          - "ooniprobe-cli"
          - "outline-ss-server"
          - "prometheus-alertmanager"
          - "prometheus-blackbox-exporter"
          - "psiphon-tunnel-core"
          - "shadowsocks-v2ray-plugin"
          - "shadowsocks-xray-plugin"
          - "sing-box"
          - "trojan-go"
          - "tun2socks"
          - "v2ray-core"
          - "wireproxy"
          - "wiretap"
          - "xray-core"
          - "xray-knife"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: git config --global user.name "Mark Pashmfouroush"
      - run: git config --global user.email "mark@markpash.me"
      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: set up nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: update package
        shell: bash
        run: |
          nix run github:Mic92/nix-update/1.3.1 -- --commit --flake ${{ matrix.package }}
          v=$(nix eval --raw .#${{ matrix.package }}.version)
          echo "package_version=$v" >> "$GITHUB_ENV"
      - name: make PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "update-${{ matrix.package }}_${{ env.package_version }}"
          delete-branch: true
          committer: "Mark Pashmfouroush <mark@markpash.me>"
          author: "Mark Pashmfouroush <mark@markpash.me>"
          title: "update ${{ matrix.package }} to ${{ env.package_version }}"
          token: ${{ github.token }}
